# Generated by Django 2.2.12 on 2020-04-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_on',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Response'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
