# Generated by Django 2.2.12 on 2020-04-26 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200426_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='asked_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='response',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
