# Generated by Django 2.2.12 on 2020-04-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200426_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.AddField(
            model_name='response',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.Post'),
            preserve_default=False,
        ),
    ]
