# Generated by Django 2.2.12 on 2020-04-27 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200426_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_on',
        ),
        migrations.AddField(
            model_name='comment',
            name='response',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Response'),
            preserve_default=False,
        ),
    ]
