# Generated by Django 2.2.12 on 2020-05-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200427_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['_created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-_created_at']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-_created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='_created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='modified_at',
            new_name='_modified_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='_created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modified_at',
            new_name='_modified_at',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='created_at',
            new_name='_created_at',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='modified_at',
            new_name='_modified_at',
        ),
    ]
