# Generated by Django 2.2.12 on 2020-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200501_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='spam',
        ),
        migrations.AddField(
            model_name='post',
            name='_toxic_class',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='toxic',
            field=models.BooleanField(null=True),
        ),
    ]
