# Generated by Django 2.2.12 on 2020-05-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200508_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='toxic',
            new_name='is_toxic',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='spam',
        ),
        migrations.RemoveField(
            model_name='response',
            name='spam',
        ),
        migrations.AddField(
            model_name='comment',
            name='_toxic_class',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_toxic',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='_toxic_class',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='is_toxic',
            field=models.BooleanField(null=True),
        ),
    ]
