# Generated by Django 2.2.12 on 2020-04-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20200426_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
    ]
