# Generated by Django 2.2.12 on 2020-05-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_user_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='_created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modified_at',
            new_name='_modified_at',
        ),
    ]
